dist: xenial

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libzmq3-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update                       ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install zeromq erlang rebar3 ; fi
  - >
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    echo "Increase the maximum number of open file descriptors on macOS" ;
    sudo sysctl -w kern.maxfiles=20480                                   ;
    sudo sysctl -w kern.maxfilesperproc=20480                            ;
    sudo launchctl limit maxfiles 10000 unlimited                        ;
    ulimit -n 20000                                                      ;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb   ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then sudo dpkg -i erlang-solutions_1.0_all.deb                                 ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then sudo apt-get -y update && sudo apt-get install esl-erlang                 ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then sudo curl -o /usr/local/bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3 ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then sudo chmod 755 /usr/local/bin/rebar3                                      ; fi

script:
  - sudo rebar3 do compile, eunit
